GET http://localhost:5000/users
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBaXN5YWgiLCJtYWlsIjoiYWlzQGdtYWlsLmNvbSIsImlhdCI6MTcxNzQ5Njc5MywiZXhwIjoxNzE3OTI4NzkzfQ.u39nWxdGm_c7PLm_BeSnaRB-riYVtdW724vKoR5M9cc

###
DELETE http://localhost:5000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBaXN5YWgiLCJtYWlsIjoiYWlzQGdtYWlsLmNvbSIsImlhdCI6MTcxNzQ5Njc5MywiZXhwIjoxNzE3OTI4NzkzfQ.u39nWxdGm_c7PLm_BeSnaRB-riYVtdW724vKoR5M9cc


###
PUT http://localhost:5000/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJuYW1lIjoiUml6a3kiLCJtYWlsIjoicml6a3lAZ21haWwuY29tIiwiaWF0IjoxNzE3NTE0MzI5LCJleHAiOjE3MTc5NDYzMjl9.77dwMj8KeNZIlKPvGyDCNZmjUlVSbv30xdVy178y5kM

Content-Type: application/json
{
    "name": "Dewa",
    "email": "mrizky@gmail.com",
    "role": "employee",
}


###
POST http://localhost:5000/community/add
Content-Type: application/json
{
    "user_id": 3,
   "caption": "Hello World"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Rizky Keren",
    "email": "rizkykeren@gmail.com",
    "role": "employee",
    "password": "123456",
    "confirmPassword" : "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "rizky@gmail.com",
    "password": "123456"    
}
